# Generated by Django 5.0.4 on 2024-05-21 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='band',
            name='biography',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synt Pop'), ('AR', 'Alternative Rock'), ('POP', 'Pop'), ('RK', 'Rock'), ('JZZ', 'Jazz'), ('BLS', 'Blues'), ('CLASS', 'Classical'), ('CNTRY', 'Country'), ('ELEC', 'Electronic'), ('REG', 'Reggae'), ('FK', 'Funk'), ('MTL', 'Metal'), ('RNB', 'Rnb'), ('SL', 'Soul'), ('FO', 'Folk'), ('LAT', 'Latin'), ('PU', 'Punk'), ('GOS', 'Gospel'), ('RP', 'Rap')], default='HH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='band',
            name='official_homepage',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='band',
            name='year_formed',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
            preserve_default=False,
        ),
    ]
