# Generated by Django 5.0.4 on 2024-05-21 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_ad_description_ad_sold_ad_type_ad_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='type',
            new_name='types',
        ),
        migrations.AddField(
            model_name='ad',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
